from scrapy.item import Item, Field


class Player(Item):
    team = Field()
    name = Field()
    age = Field()
    goals = Field()
    assists = Field()
    passes = Field()
    tackles = Field()
    position = Field()
    appearances = Field()
    saves = Field()
    penalties = Field()
    punches = Field()
    highclaims = Field()
    catches = Field()
    sweeperclearances = Field()
    throwouts = Field()
    goalkicks = Field()
    yellowcards = Field()
    redcards = Field()
    fouls = Field()
    cleansheets = Field()
    goalsconceded = Field()
    errorsleadingtogoal = Field()
    owngoals = Field()
    passespermatch = Field()
    accuratelongballs = Field()
    goalspermatch = Field()
    goalswithheader = Field()
    goalswithrightfoot = Field()
    goalswithleftfoot = Field()
    penaltiesscored = Field()
    goalsfromfreekick = Field()
    shots = Field()
    shotsontarget = Field()
    shootingaccuracy = Field()
    hitwoodwork = Field()
    bigchancesmissed = Field()
    crosses = Field()
    bigchancescreated = Field()
    blockedshots = Field()
    interceptions = Field()
    clearances = Field()
    headedclearance = Field()
    tacklesuccess = Field()
    recoveries = Field()
    duelswon = Field()
    duelslost = Field()
    successful5050s = Field()
    aerialbattleswon = Field()
    aerialbattleslost = Field()
    crossaccuracy = Field()
    troughballs = Field()




